const PictureItem = [
    {
      id: '1',
      title: 'Little Krishna',
      price: '399.99',
      writtenby:"Vilas Shubha",
      publishedby:"Wonder House Books",
      grade:"1st - 2nd",
      videolink:"https://youtu.be/vlXgBwyw3Kc?si=FIMuL6WRPPAenFzQ",
      description:"Little Krishna is a delightful children's book that brings to life the captivating stories of Krishna's childhood. Filled with vibrant illustrations and engaging narratives, this book introduces young readers to the mischievous yet divine adventures of Krishna. Through tales of bravery, wisdom, and playfulness, children will learn valuable lessons about love, friendship, and the triumph of good over evil. Ideal for early grade readers, Little Krishna is a perfect addition to any child's library, offering both educational and entertainment value.",
      img: 'https://m.media-amazon.com/images/I/51k0rSsSZ0L._SX342_SY445_.jpg',
    },
    {
      id: '2',
      title: 'Agbar and Birbal',
      price: '195',
      writtenby:"Yamini Rachna Bhola",
      publishedby:"Diamond Books",
      grade:"1st - 2nd",
      videolink:"https://youtu.be/8LP-2uy7z1Y?si=wb-3IgXktjlFIefm",
      description:"The book Akbar and Birbal is a collection of tales about the legendary duo from Indian folklore, Emperor Akbar and his witty advisor, Birbal. These stories are popular for their moral lessons, cleverness, and humor. The tales typically highlight Birbal's sharp intellect and ability to solve complex problems with ease, often outsmarting those who challenge him or try to deceive the emperor.",
      img: 'https://m.media-amazon.com/images/I/615SaD9oHTL._SY445_SX342_.jpg',
       
    },
    {
      id: '3',
      title: 'The Rich Man and the Monkey ',
      price: '699.99',
      writtenby:"Idries Shah",
      publishedby:"Diamond Books",
      grade:"1st - 2nd",
      videolink:"https://youtu.be/Ee1SCjnik10?si=LiXSgGpQo4wT3pJh",
      description:"The Rich Man and the Monkey is a captivating children's book by Idries Shah, illustrated by Natasha Delmar. This story is part of Shah's larger body of work aimed at sharing the rich tradition of Eastern folklore with modern audiences.",
      img: 'https://cdn-jdbfh.nitrocdn.com/XTbOLvleLvLTNFoFUdqUzTQBhtILBLqa/assets/images/optimized/rev-4a653e8/idriesshahfoundation.org/wp-content/uploads/2024/05/childrensbook_TheRichManAndTheMonkey.png',
    },
    {
      id: '4',
      title: 'The Onion',
      price: '599.99',
      writtenby:"Idries Shah",
      publishedby:"Hoopoe Books",
      grade:"1st - 2nd",
      videolink:"https://youtu.be/15kvWkWxjbU?si=wIMOT2ULcQuouetv",
      description:"The Onion is a charming childrens book that delves into the rich tapestry of folklore from different cultures. Written by Idries Shah, it features enchanting illustrations that complement the engaging narrative.",
      img: 'https://cdn-jdbfh.nitrocdn.com/XTbOLvleLvLTNFoFUdqUzTQBhtILBLqa/assets/images/optimized/rev-4a653e8/idriesshahfoundation.org/wp-content/uploads/2022/03/theonion_bookcover-1.png',
    },
    {
      id: '5',
      title: '108 Panchatantra Stories Book',
      price: '599.99',
      writtenby:"Om Books Editorial Team",
      publishedby:"Om Books International",
      grade:"1st - 2nd",
      videolink:"https://www.youtube.com/watch?v=q80YiJ6Dfb0&pp=ygUdMTA4IFBhbmNoYXRhbnRyYSBTdG9yaWVzIEJvb2s%3D",
      description:"The 108 Panchatantra Stories Book is a captivating collection of tales from the ancient Indian classic, the Panchatantra. These stories have been passed down through generations and are known for their engaging narratives and timeless wisdom.",
      img: 'https://cdn.fcglcdn.com/brainbees/images/products/438x531/17974310a.webp',
      
    },
    {
      id: '6',
      title: 'The Magic of the Lost Story',
      price: '599.99',
      writtenby:"Sudha Murty",
      publishedby:"Puffin Books",
      grade:"1st - 2nd",
      videolink:"https://youtu.be/3wzpODdJBII?si=RAA-sCbsdrSZ37SO",
      description:"The Magic of the Lost Story is a captivating children's book that tells the enchanting tale of young adventurers who discover a forgotten storybook. As they delve into its pages, they are transported into a magical world where they must embark on a quest to save a kingdom trapped in time. Through their journey, they encounter whimsical characters, solve puzzles, and learn the importance of courage, friendship, and the timeless power of storytelling. The narrative emphasizes the boundless possibilities of imagination and the adventure that comes with discovering new worlds within the pages of a book.",
      img: 'https://m.media-amazon.com/images/I/51QxnVcjmvL._SY445_SX342_.jpg',
      
    },
    {
      id: '7',
      title: 'Stories of Tenali Raman',
      price: '599.99',
      writtenby:"Meena Arora",
      publishedby:"Om Books International",
      grade:"1st - 2nd",
      videolink:"https://youtu.be/Qnx_GOur8Rg?si=jbdHD5kFJ5apNlUZ",
      description:"Stories of Tenali Raman is a delightful collection of tales centered around the legendary poet and jester, Tenali Raman, known for his wit, wisdom, and humor. Set in the vibrant court of King Krishnadevaraya of the Vijayanagara Empire, these stories showcase Tenali Raman's clever problem-solving abilities and his knack for turning seemingly impossible situations to his advantage.",
      img: 'https://m.media-amazon.com/images/I/61MzrSdwJfL._SY445_SX342_.jpg',
      
    },
    {
      id: '8',
      title: 'The Way Cool Butterfly',
      price: '599.99',
      writtenby:"Alan Madison",
      publishedby:"Schwartz & Wade",
      grade:"1st - 2nd",
      videolink:"https://youtu.be/Nd-wG1MnI0U?si=zjLbmvQqSbIwYpDJ",
      description:"Dive into the vibrant world of butterflies with The Way Cool Butterfly, a captivating book that blends fascinating facts, stunning illustrations, and engaging stories about one of nature's most enchanting creatures. This book is perfect for young readers, nature enthusiasts, and anyone with a sense of wonder about the natural world.",
      img: 'https://m.media-amazon.com/images/I/715OJD1AnPL._AC_UY218_.jpg',
      
    },
    {
      id: '9',
      title: 'Being Frank',
      price: '599.99',
      writtenby:"Donna W. Earnhardt",
      publishedby:"Flashlight Press",
      grade:"1st - 2nd",
      videolink:"https://youtu.be/NqBzMd3FGJg?si=yP43GAbzfxP97Zjf",
      description:"Being Frank is a charming and insightful children's book that explores the value of honesty through the eyes of a young boy named Frank. Known for his unfiltered honesty, Frank learns that while telling the truth is important, how you say it can make all the difference.",
      img: 'https://m.media-amazon.com/images/I/81kyeKDax9L._AC_UY218_.jpg',
     
    },
    {
      id: '10',
      title: 'The Mess That We Made',
      price: '599.99',
      writtenby:"Michelle Lord",
      publishedby:"Flashlight Press",
      grade:"1st - 2nd",
      videolink:"https://youtu.be/lR_9-iF_mYg?si=sKLy-9qAhIbSu6h0",
      description:"The Mess That We Made is an impactful and beautifully illustrated children's book that addresses the urgent issue of ocean pollution. Through its engaging narrative and evocative artwork, the book aims to inspire young readers and their families to take action in protecting our planet.",
      img: 'https://m.media-amazon.com/images/I/61MJP1X4lyL._SX342_SY445_.jpg',
    },
    {
      id: '11',
      title: 'A Tale of Two Beasts',
      price: '599.99',
      writtenby:"Fiona Roberton",
      publishedby:"Kane Miller Books",
      grade:"1st - 2nd",
      videolink:"https://youtu.be/zCkOocQGtDU?si=JTNB2Dtvc7JHZ64O",
      description:"A Tale of Two Beasts is a delightful and thought-provoking children's book by Fiona Roberton that explores the theme of perspective through two different viewpoints. This beautifully illustrated story captures the importance of understanding and empathy, making it a perfect read for children and adults alike.",
      img: 'https://m.media-amazon.com/images/I/91dqlmuX3rL._AC_UY218_.jpg',
      
    },
    {
      id: '12',
      title: 'Arnie the Doughnut',
      price: '599.99',
      writtenby:"Laurie Keller",
      publishedby:" Henry Holt and Co.",
      grade:"1st - 2nd",
      videolink:"https://youtu.be/xcXo0Pc7GPo?si=TAApb99CV1bz8aPn",
      description:"Arnie the Doughnut is a whimsical and entertaining children's book written and illustrated by Laurie Keller. It tells the hilarious and heartwarming story of Arnie, a freshly baked doughnut who discovers that being a doughnut isn't exactly what he expected. With its playful narrative and vibrant illustrations, this book is a delightful read for young readers and their families.",
      img: 'https://m.media-amazon.com/images/I/819695bDe5L._AC_UY218_.jpg',

    },
  ];
  
  export default PictureItem;